name: 'Build and install Tarantool'
description: 'Builds Tarantool from source and installs it'
inputs:
  cc:
    default: gcc
  cxx:
    default: g++
  cmake_defines:
    required: false
  ref:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "Building Tarantool ${{inputs.ref}}"
        mkdir -p ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        git clone -n https://github.com/tarantool/tarantool.git
        cd tarantool
        git checkout ${{inputs.ref}}
        git submodule update --init --recursive
        CC=${{inputs.cc}} CXX=${{inputs.cxx}} cmake -B ${{github.workspace}}/build/tarantool/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{inputs.cmake_defines}}
        cmake --build ${{github.workspace}}/build/tarantool/build --parallel --config ${{env.BUILD_TYPE}}
        cd ${{github.workspace}}/build/tarantool/build && sudo make install
      shell: bash
