
name: 'Build httpng'
description: 'Builds httpng from source'
runs:
  using: "composite"
  steps:
    - run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      shell: bash
