
name: 'Build httpng'
description: 'Builds httpng from source'
inputs:
  cc:
    default: gcc
  cxx:
    default: g++
  cmake_defines:
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        CC=${{inputs.cc}} CXX=${{inputs.cxx}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{inputs.cmake_defines}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      shell: bash
