name: Test buildability, then regressions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{matrix.os}}

    steps:
    - name: Where we are?
      run: uname -a; cat /etc/os-release || cat /etc/issue || python -m platform || true

    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build and install Tarantool
      uses: ./.github/actions/build-tarantool
      with:
        cc: 'clang'
        cxx: 'clang++'
        cmake_defines: '-DENABLE_ASAN=ON'

    - name: Build httpng
      uses: ./.github/actions/build-httpng
      with:
        cc: 'clang'
        cxx: 'clang++'
        cmake_defines: '-DENABLE_ASAN=ON'

    - name: Install luatest
      working-directory: ${{github.workspace}}/build
      # Ignore all errors (some are caused by ASAN in Tarantool)
      run: ASAN_OPTIONS=detect_leaks=0 ${{github.workspace}}/build/tarantool/build/extra/dist/tarantoolctl rocks install luatest

    - name: Test HTTPNG (luatest)
      working-directory: ${{github.workspace}}
      # FIXME: luatest doesn't understand neither absolute paths nor ".."!
      # FIXME: Should enable Leak Sanitizer some day...
      run: ASAN_OPTIONS=detect_leaks=0 LUA_CPATH="${{github.workspace}}/build/?.dylib;${{github.workspace}}/build/?.so" build/.rocks/bin/luatest -v -r 5 tests/all.lua
