name: Test buildability, then regressions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        tarantool-ref: ['1.10', '2.7']
        enable_asan: [true, false]
        exclude:
          - os: 'macos-latest'
            tarantool-ref: '1.10'
    runs-on: ${{matrix.os}}

    steps:
    - name: Where we are?
      run: uname -a; cat /etc/os-release || cat /etc/issue || python -m platform || true

    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build and install Tarantool (with ASAN)
      uses: ./.github/actions/build-tarantool
      if: ${{matrix.enable_asan}}
      with:
        cc: 'clang'
        cxx: 'clang++'
        cmake_defines: '-DENABLE_ASAN=ON'
        ref: ${{matrix.tarantool-ref}}

    - name: Build and install Tarantool (without ASAN)
      uses: ./.github/actions/build-tarantool
      if: ${{!matrix.enable_asan}}
      with:
        cc: 'gcc'
        cxx: 'g++'
        cmake_defines: ''
        ref: ${{matrix.tarantool-ref}}

    - name: Build httpng
      uses: ./.github/actions/build-httpng
      with:
        enable_asan: ${{matrix.enable_asan}}

    - name: Add entries to /etc/hosts
      run: sudo tests/mangle_etc_hosts.sh

    - name: Install luatest
      working-directory: ${{github.workspace}}/build
      # Ignore all errors (some are caused by ASAN in Tarantool)
      run: ASAN_OPTIONS=detect_leaks=0 ${{github.workspace}}/build/tarantool/build/extra/dist/tarantoolctl rocks install luatest

    - name: Test HTTPNG (luatest)
      working-directory: ${{github.workspace}}
      # FIXME: luatest doesn't understand neither absolute paths nor ".."!
      # FIXME: Should enable Leak Sanitizer some day...
      run: ASAN_OPTIONS=detect_leaks=0 LUA_CPATH="${{github.workspace}}/build/?.dylib;${{github.workspace}}/build/?.so" build/.rocks/bin/luatest -v -r 1 tests/all.lua --shuffle all
